#!/bin/bash

ZENITY=/usr/bin/zenity 

CAMINHO=$*
ARQUIVO=$(basename $CAMINHO)

EXTENSION=$(echo $ARQUIVO | sed -r 's#^*\.([a-zA-Z0-9]{1,5})$#\1#g')
EXTENSION=`echo "$ARQUIVO" | cut -d'.' -f2 | tr A-Z a-z`

convert_to_avi()
{
	INPUT=$1
	OUTPUT=$(echo $INPUT | sed -r "s#\.[A-Za-z0-9]{1,4}\$#.avi#g")
    ffmpeg -i $INPUT -f avi -r 29.97 -vcodec libxvid -vtag XVID -s 640x480 -aspect 4:3 -maxrate 1800kb -b 1500kb -qmin 3 -qmax 5 -bufsize 4096 -mbd 2 -bf 2 -flags +4mv -trellis -aic -cmp 2 -subcmp 2 -g 300 -acodec libmp3lame -ar 48000 -ab 128kb -ac 2 $OUTPUT
}

convert_to_flv()
{
	INPUT=$1
	OUTPUT=$(echo $INPUT | sed -r "s#\.[A-Za-z0-9]{1,4}\$#.flv#g")
	ffmpeg -i $INPUT -vcodec flv -f flv -r 29.97 -s 320x240 -aspect 4:3 -b 300kb -g 160 -cmp dct  -subcmp dct  -mbd 2 -flags +aic+cbp+mv0+mv4 -trellis 1 -ac 1 -ar 22050 -ab 56kb $OUTPUT
}


convert_mp4()
{
	INPUT=$1
    converto_to_flv $INPUT	
    converto_to_avi $INPUT	
	$ZENITY --info --text="Arquivo $ARQUIVO é formato MP4. Foi convertido para FLV e AVI."	
}

convert_avi()
{
	INPUT=$1
    converto_to_flv $INPUT	
	$ZENITY --info --text="Arquivo $ARQUIVO foi convertido para FLV."	
}

convert_flv()
{
	INPUT=$1
    converto_to_avi $INPUT	
	$ZENITY --info --text="Arquivo $ARQUIVO é formato FLV. Foi convertido para AVI."	
}


if [ $EXTENSION == "mp4" ]
then
	convert_mp4 $CAMINHO

elif [ $EXTENSION == "avi" ]
then
	convert_avi $CAMINHO

elif [ $EXTENSION == "mpg" ]
then
	convert_mp4 $CAMINHO

elif [ $EXTENSION == "mpeg" ]
then
	convert_mp4 $CAMINHO

elif [ $EXTENSION == "divx" ]
then
	convert_mp4 $CAMINHO

elif [ $EXTENSION == "flv" ]
then
	convert_flv $CAMINHO
fi


